name: Metronome

channels:
  - conda-forge
  - pyviz

dependencies:
  - python=3.10
  - ipython=8.18.1
  - pip=23.3.1
  - numpy=1.26.0
  - pandas=2.1.4
  - scipy=1.15.3
  - scikit-learn=1.3.2
  - scikit-image=0.20.0
  - joblib=1.3.2
  - tqdm=4.66.4
  - matplotlib=3.10.7
  - pillow=10.0.1
  - imageio=2.19.3
  - imageio-ffmpeg=0.4.7
  - netcdf4=1.7.1
  - lxml=4.9.3
  - spyder=5.5.0
  - spyder-kernels=2.5.0
  - pip:
      - colour-demosaicing==0.2.6
      - opencv-python==4.8.1.78
      - Metashape-...-win_amd64.whl